version: "3"
services:
  app:
    container_name: DevOps_Project
    image: firstimage/devops_image
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    volumes:
      - app_data:/app/data

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"

    volumes:
      - db:/var/lib/mysql

volumes:
  app_data:
  db: