version: "3"
services:
  app:
    container_name: DevOps_Project
    image: ayou1234/my-java-app  # Remplacez par l'image Docker de votre application
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:h2:file:/data/db",
        "spring.datasource.driverClassName" : "org.h2.Driver",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.H2Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8082:8082"  # Mappage du port de votre application sur l'hôte
    volumes:
      - app_data:/data

volumes:
  app_data:  # Définissez le volume app_data
