version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: devops_project
    ports:
      - 8082:8082
    container_name: devops_project
    environment:
      - SERVER_PORT=8082
      - SPRING_PROFILES_ACTIVE=prod,test
      - SPRING_DATASOURCE_URL=jdbc:mysql://prod-db:${PROD_DB_PORT}/devops_prod?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - DOCKER_USERNAME=nasreddine007
      - DOCKER_PASSWORD=dckr_pat_y-bDuwILc-796Xs4Pe_CzP87zTM
      - MANAGEMENT.ENDPOINTS.WEB.EXPOSURE.INCLUDE=*
      - MANAGEMENT.ENDPOINT.PROMETHEUS.ENABLED=true
      - MANAGEMENT.ENDPOINT.METRICS.ENABLED=true
      - management.endpoint.health.show-details=always
    depends_on:
      - prod-db
  prod-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops_prod
    ports:
      - 3308:3306
    volumes:
      - db_data_prod:/var/lib/mysql
    container_name: prod_db
  test-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops_test
    ports:
      - 3309:3306
    volumes:
      - db_data_test:/var/lib/mysql
    container_name: test_db

volumes:
  db_data_prod:
  db_data_test: