version: "3"
services:
  app:
    container_name: DevOps_Project
    image: firstimage/springapp # Replace with the actual image and tag
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8082:8082"  # Map your application's port to the host
    depends_on:
      - mysqldb  # Ensure the MySQL service is started before the application
    volumes:
      - app_data:/app/data

  mysqldb:
    container_name: mysqldb
    image: mysql:latest  # You can use a different version if needed
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"  # Map MySQL's port to the host

    volumes:
      - db:/var/lib/mysql

volumes:
  app_data:  # Define the app_data volume
  db: