version: "3"
services:
  app:
    container_name: DevOps_Project
    build:
      context: .
      dockerfile: Dockerfile
    # image: maryem200/maryemimage  # Replace with the actual image and tag
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devops?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:8082"  # Map your application's port to the host
    depends_on:
      - mysqldb  # Ensure the MySQL service is started before the application
    # volumes:
      # - app_data:/app/data
    networks:
      - my-network
  db:
    container_name: db
    image: mysql:8.0.27  # You can use a different version if needed
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"  # Map MySQL's port to the host
    volumes:
      - db:/var/lib/mysqlz
    networks:
      - my-network
volumes:
  # app_data:  # Define the app_data volume
  db:

networks:
  my-network:
    driver: bridge
